### ISSUE TITLE
结果不正确

### ISSUE THREAD

**Issue by whk6688** [fly12357/CTR_Xlearn#1]
首先很荣幸能看到你的代码，
目前有问题想咨询您：
用你提供的预测方式，跟xlearn 自带的预测结果不同：
ffm_model.setTest("./single_predict_data")  # 测试数据
ffm_model.predict("./model.out", "./output1.txt")

我用的是xlearn0.44， 甚至xlearn新开发的api也不行
string = "0,1:22166:1,2:22169:1,3:22175:1,4:22302:1,5:0:1,6:6:1,7:16:1,8:18:1,9:39:1,10:1062:1,11:1079:1,12:1089:1,13:1092:1,14:1094:1,15:1096:1,16:1098:1,17:1100:1,18:1102:1,19:1104:1,20:1107:1,21:1108:1,22:1110:1,23:1114:1,24:1564:1,25:20787:1,26:20804:1,27:20914:1,28:22161:1,29:181:1,30:20804:1,31:20993:1,32:1117:1,33:1062:1,34:1474:1,35:1095:1,36:1096:1,37:1104:1,38:1101:1,39:1080:1,29:181:1,30:20804:1,31:20993:1,32:1117:1,33:1062:1,34:1474:1,35:1095:1,36:1096:1,37:1104:1,38:1101:1,39:1080:1"
r = string.split(',')
X = [0]*22320
field_map = [0]*22320
for index, i in enumerate(r):
    if index == 0:
        continue
    field_value = int(i.split(':')[0])
    feature_index = int(i.split(':')[1])
    feature_value = int(i.split(':')[2])
    X[feature_index] = feature_value
    field_map[feature_index] = field_value

X = np.array(X)
X = X.reshape((1, -1))
X = check_array(X, accept_sparse=['csr'])
test_set = xl.DMatrix(X, None, field_map=field_map)
fm_model = xl.create_ffm()  # Use factorization machine
fm_model.setTest(test_set)
fm_model.disableNorm()
pred = fm_model.predict('./model.out')
print(pred)

想问您遇到过此问题吗。是否xlearn有了一些额外的逻辑？

非常感谢您的回答。

**Comment by fly12357** [comment]
> 首先很荣幸能看到你的代码，
> 目前有问题想咨询您：
> 用你提供的预测方式，跟xlearn 自带的预测结果不同：
> ffm_model.setTest("./single_predict_data") # 测试数据
> ffm_model.predict("./model.out", "./output1.txt")
> 
> 我用的是xlearn0.44， 甚至xlearn新开发的api也不行
> string = "0,1:22166:1,2:22169:1,3:22175:1,4:22302:1,5:0:1,6:6:1,7:16:1,8:18:1,9:39:1,10:1062:1,11:1079:1,12:1089:1,13:1092:1,14:1094:1,15:1096:1,16:1098:1,17:1100:1,18:1102:1,19:1104:1,20:1107:1,21:1108:1,22:1110:1,23:1114:1,24:1564:1,25:20787:1,26:20804:1,27:20914:1,28:22161:1,29:181:1,30:20804:1,31:20993:1,32:1117:1,33:1062:1,34:1474:1,35:1095:1,36:1096:1,37:1104:1,38:1101:1,39:1080:1,29:181:1,30:20804:1,31:20993:1,32:1117:1,33:1062:1,34:1474:1,35:1095:1,36:1096:1,37:1104:1,38:1101:1,39:1080:1"
> r = string.split(',')
> X = [0]*22320
> field_map = [0]*22320
> for index, i in enumerate(r):
> if index == 0:
> continue
> field_value = int(i.split(':')[0])
> feature_index = int(i.split(':')[1])
> feature_value = int(i.split(':')[2])
> X[feature_index] = feature_value
> field_map[feature_index] = field_value
> 
> X = np.array(X)
> X = X.reshape((1, -1))
> X = check_array(X, accept_sparse=['csr'])
> test_set = xl.DMatrix(X, None, field_map=field_map)
> fm_model = xl.create_ffm() # Use factorization machine
> fm_model.setTest(test_set)
> fm_model.disableNorm()
> pred = fm_model.predict('./model.out')
> print(pred)
> 
> 想问您遇到过此问题吗。是否xlearn有了一些额外的逻辑？
> 
> 非常感谢您的回答。

是FM还是FFM？ 我看你上面提供的不一致啊！

**Comment by fly12357** [comment]
> "0,1:22166:1,2:22169:1,3:22175:1,4:22302:1,5:0:1,6:6:1,7:16:1,8:18:1,9:39:1,10:1062:1,11:1079:1,12:1089:1,13:1092:1,14:1094:1,15:1096:1,16:1098:1,17:1100:1,18:1102:1,19:1104:1,20:1107:1,21:1108:1,22:1110:1,23:1114:1,24:1564:1,25:20787:1,26:20804:1,27:20914:1,28:22161:1,29:181:1,30:20804:1,31:20993:1,32:1117:1,33:1062:1,34:1474:1,35:1095:1,36:1096:1,37:1104:1,38:1101:1,39:1080:1,29:181:1,30:20804:1,31:20993:1,32:1117:1,33:1062:1,34:1474:1,35:1095:1,36:1096:1,37:1104:1,38:1101:1,39:1080:1"

还有一点， 我这个版本实现的时候加了instance 归一化的操作， 我看你训练的时候好像 disableNorm了。 这也可能是不一致的原因～

有问题再联系哈～
