### ISSUE TITLE
预测速度不快

### ISSUE THREAD

**Issue by whk6688** [fly12357/CTR_Xlearn#2]
您好，按照您给的方法，预测主要分成两部分，线性和非线性两块，上线后发现了一个问题，预测两百个条目，当压力上来时，较慢，如果超过100毫秒算超时的话，超时挺多的，我已将模型和预测的条目都缓存到本地了，想问问有没有，更好的办法，提升预测的速度，谢谢！（60个field， 8w向量，模型500w行）。

**Comment by fly12357** [comment]
> 您好，按照您给的方法，预测主要分成两部分，线性和非线性两块，上线后发现了一个问题，预测两百个条目，当压力上来时，较慢，如果超过100毫秒算超时的话，超时挺多的，我已将模型和预测的条目都缓存到本地了，想问问有没有，更好的办法，提升预测的速度，谢谢！（60个field， 8w向量，模型500w行）。

你是用python实现？ 线上预测最好换c++或者Java， 我写这个主要为了理解原理~ 如果C++用的熟的话， 你可以看看xlearn中的源代码， 把源代码中 load_model 与 predict这两部分拆开~，
